### ISSUE TITLE
What is the purpose of the Subscription Deactivation Notification Message

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#38]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.112.8

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The Subscription Deactivation Notification Message does not seem to be aligned with the Subscriptions Framework, and it is not clear why we need this message. 

If the concern is that the client does not know when a subscription is deactivated due to an error state, well it seems unlikely the client will be in a position to receive the deactivation message in that case anyway. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Remove the Subscription Deactivation Notification Message. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
Discussed during F2F. 
This interaction extends the Subscription framework. It does not concern errors.

The purpose of this message is to notify about the deactivation of the subscription when a Subscription deactivation occurs:
- performed by the Resource Notification Broker at the termination time of the subscription or, 
- performed with the [ITI-110] Resource Subscription transaction, by the same Resource Notification Subscriber that made the subscription 
- performed with the [ITI-110] Resource Subscription transaction, by another Resource Notification Subscriber (tipical use case is when subscriptions management is performed in order to clean subscription)  

In the first and third case the deactivation is not performed by the Resource Notification Subscriber that made the Subsription; in this way it could promptly manages the deactivation. 

In the second case it could be sure that the deactivation has been correctly done.

**Comment by slagesse-epic** [comment]
In the first case, I think the Resource Notification Subscriber should remember the expiration date it set on the subscription, so its termination does not need to be communicated. 

The Resource Notification Subscriber also isn't the Actor that receives notification messages, so I don't see how requiring the server to send a deactivation message helps it. I think in the FHIR Subscriptions framework it should be the responsibility of the subscriber to monitor its subscriptions (with ITI-113), which it must do anyway because it is always possible a connectivity failure could cause it to stop receiving notifications.

**Comment by gpavan19** [comment]
Usually the Resource Notification Subscriber and the Resource Notification Recipient are implemented within the same application but they are related to different functionality of the application. Tipically a notification is a trigger for other event that could be performed punctually.

In the first case, the notification should be an adding value to notify the Resource Notification Recipient that it will not receive notification anymore. In that case the appliaction portion related to the Resource Notification Recipient can be able to tempestive manage it.
Also, if we consider an infrastructure where there is a management application that implement only the Subscriber capable of cleaning the Subscription, when this application perform the deactivation, promptly notify that the Subscription goes off should grant a tempestive management if needed.

The Resource Notification Subscriber usually could monitor its subscription in a configured interval of time. 
Sure, the it is always possible a connectivity failure. But so why in this case a Resource Notification Broker should send the Hearthbeat notification with status = error ? Because it may be useful to give early warning that an error occurs instead of just relying on subscription monitoring with ITI-113. And this is the same in the case of deactivation.


If the concer is about to require that the Resource Notification Broker SHALL support this type of notification, maybe it could be address as a SHOULD. @slagesse-epic

**Comment by slagesse-epic** [comment]
I am fine with making it a SHOULD.

**Comment by gpavan19** [comment]
made it a SHOULD in text; also explicit in capabilityStatement for Broker
