### ISSUE TITLE
Use Case #6 Problematic

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.DSUBm#42]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:54.4.2.6

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Use Case #6 shows use of the Updates to document sharing resources option, but the use case is a problematic demonstration of that option. 

In Use Case #6, the document is not visible to the subscriber when it is created due to policy. Later, the document confidentiality code is updated, which allows the document to be visible to the subscriber and an update notification is sent. 

I don't think this is a good example of the Updates to document sharing resources option, since in this case, from the perspective of the subscriber, the document has been "created" when it was updated. And I think the Resource Notification Broker should be allowed to treat it as such (meaning a create notification would be sent even when the option is not implemented)

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Revise Use Case #6 to present a case where the Resource Notification Recipient needs to learn of an update to a DocumentReference Resource that they are already aware of. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by gpavan19** [comment]
We don't think so.
This is exactly the use case that demonstrates how the option can be use to also become aware of update events that would otherwise be lost.

Furthermore, the notification must be interpreted as "there is a document which, after having undergone an update, matches your subscription and which may be of interest to you". And that is the prospective the subscriber shall have.

Also, the logic for a Resource Notification Broker to treat an update as a create is based on the fact that the subscriber has not be aware of the document yet, but the notification is not the only way to be aware of a document. 
And also this shall be avaluate for all the subscribers to which the notification shall be send and, based on that, it could generate different notification triggered from the same event.

**Comment by slagesse-epic** [comment]
I am not saying it is wrong to send an update notification, I am saying this is not a good example of the need for an update option, because from the Notification Recipient's perspective it is not an update.

**Comment by gpavan19** [comment]
Ok, I think that we can maintain this use case and we can add a simplier use case above this one to made the readers be aware why they should use the Option in a simplier scenario.

sounds good ? @slagesse-epic

**Comment by slagesse-epic** [comment]
Sure
