### ISSUE TITLE
DSUBm_001: Should DSUBm use the subscription backport for FHIR R4 or R4B?

### ISSUE THREAD

**Issue by scontento** [IHE/ITI.DSUBm#9]
(see DSUBm_001 in issues.html)
This Profile define a Subscription framework using R4B version of FHIR, in order to improve the subscription functional from the R4 version. Are there any compelling arguments to use R4 version of FHIR?

**Comment by JohnMoehrke** [comment]
Given that the IG Publisher will not allow profiling across versions, the use of R4B makes DSUBm an island on FHIR R4B, where as all other ITI profiles use R4. 
- One response is that the subscription endpoint can be a different microservice and thus the difference between R4 and R4B is not a worry
- Another response is that one can not have a single FHIR server that supports both R4 and R4B

**Comment by RicardoQuintano** [comment]
Based on the preliminary results of the "FHIR Implementer Survey," R4 is the most adopted version (https://chat.fhir.org/#narrow/stream/179160-social/topic/FHIR.20Implementer.20Survey/near/412120525)

On the other hand, R4B seems to be more "future proof" than R4. This can be useful, in case this IG (Profile) is converted to newer versions of FHIR.

**Comment by GinoCanessa** [comment]
I had filed this myself as issue #65 , but I think that DSUBm should move to FHIR R4.

With the backport IG STU 1.2 (currently in ballot), there is feature parity between R4 and R4B for subscriptions.  Tooling improvements have made it so that you can define a topic in an IG using a newer format and it will automatically down convert to an R4 Basic resource and use cross-version extensions.

While R4B looks better on paper, FHIR R4 is much more widely implemented and I expect most people to skip R4B.

**Comment by scontento** [comment]
Hi @GinoCanessa, 

Could you point me to the tools to convert the SubscriptionTopic to R4 BAsic resource?

**Comment by gpavan19** [comment]
discuss with the commmitee

agree R4 is better 

we procede to switch to R4, maintaining the transaction
